project:
  type: website

website:
  title: "STA220"
  site-url: "https://sta220.github.io/documentation/"
  navbar:
    left:
      - index.qmd
      - Lecture1.qmd
      - ws1.qmd
      - Lecture2.qmd
      - seminar_legal.qmd
      - Lecture3.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
revealjs: 
  theme: dark
  transition: fade
  slide-number: true
  css: styles.css
  smaller: true
  scrollable: true